.TH skyldav 3 "June 11th, 2013" "version 0.1" "Skyld AV overview"
.SH NAME
skyldav \- Skyld AV on access virus scanner
.SH SYNOPSIS
.B skyldav
.RB [ \-c
.IR configfile ]
.RB [ \-d ]
.RB [ \-h ]
.SH DESCRIPTION
.PP
Skyld AV provides on access virus scanning for Linux.
.TP
.B \-c \fBconfigfile\fR
path to configuration file
.TP
.B \-d
daemonize
.TP
.B \-h
help
.SH AUTHOR
Heinrich Schuchardt <xypron.glpk@gmx.de>
.SH FILES
The location of the configuration file defaults to '/etc/skyldav.conf'.
.SH SEE ALSO
Further documentation and examples can be found in the documentation
path, which defaults to /usr/local/share/doc/skyldav
