.TH SKYLDAVNOTIFY 1 "May 6th, 2016" "version 0.6" "Skyld AV notification"
.SH NAME
skyldavnotify \- Desktop notification for Skyld AV
.SH SYNOPSIS
.B skyldavnotify
.RB [ \-h ]
.RB [ \-v ]
.SH DESCRIPTION
.PP
This program notifies the user of a windows manager like KDE or GNOME if
Skyld AV detected malware. Typical usage is to start this file using a
desktop link
.IR /etc/xdg/autostart/skyldavnotify.desktop .
.PP
.TP
.B \-h
Print usage information.
.TP
.B \-v
Print the program version and licensing information.
.SH AUTHOR
Heinrich Schuchardt <xypron.glpk@gmx.de>
.SH SEE ALSO
.BR sykldav (1)
.PP
Further documentation and examples can be found in the documentation
path, which defaults to
.IR /usr/local/share/doc/skyldav .
